/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "FreeRTOS.h"
#include "task.h"

#define SCB_CPACR      (*(volatile uint32_t *)0xE000ED88U)
#define RCC_AHB1ENR    (*(volatile uint32_t *)0x40023830U)

#define GPIOD_MODER    (*(volatile uint32_t *)0x40020C00U)
#define GPIOD_OTYPER   (*(volatile uint32_t *)0x40020C04U)
#define GPIOD_OSPEEDR  (*(volatile uint32_t *)0x40020C08U)
#define GPIOD_PUPDR    (*(volatile uint32_t *)0x40020C0CU)
#define GPIOD_ODR      (*(volatile uint32_t *)0x40020C14U)
#define GPIOD_BSRR     (*(volatile uint32_t *)0x40020C18U)

#define GPIODEN        (1U << 3)
#define LED_MASK       ((1U << 12) | (1U << 13) | (1U << 14) | (1U << 15))

typedef struct
{
	uint32_t pin;
	TickType_t period;
} LedTaskConfig;

static const LedTaskConfig led_task_config[] =
{
	{ (1U << 12), pdMS_TO_TICKS(250U)  },
	{ (1U << 13), pdMS_TO_TICKS(500U)  },
	{ (1U << 14), pdMS_TO_TICKS(750U)  },
	{ (1U << 15), pdMS_TO_TICKS(1000U) }
};

void SystemInit(void)
{
	SCB_CPACR |= (0xFU << 20);
}

static void led_init(void)
{
	volatile uint32_t dummy_read;

	RCC_AHB1ENR |= GPIODEN;
	dummy_read = RCC_AHB1ENR;
	(void)dummy_read;

	GPIOD_MODER &= ~((3U << 24) | (3U << 26) | (3U << 28) | (3U << 30));
	GPIOD_MODER |=  ((1U << 24) | (1U << 26) | (1U << 28) | (1U << 30));

	GPIOD_OTYPER &= ~LED_MASK;
	GPIOD_OSPEEDR &= ~((3U << 24) | (3U << 26) | (3U << 28) | (3U << 30));
	GPIOD_PUPDR &= ~((3U << 24) | (3U << 26) | (3U << 28) | (3U << 30));
	GPIOD_ODR &= ~LED_MASK;
}

static void led_task(void *argument)
{
	const LedTaskConfig *config = (const LedTaskConfig *)argument;
	TickType_t last_wake_time = xTaskGetTickCount();
	uint32_t led_is_on = 0U;

	for (;;)
	{
		/* BSRR updates one GPIO bit atomically, so tasks cannot lose writes. */
		GPIOD_BSRR = (led_is_on == 0U) ? config->pin : (config->pin << 16U);
		led_is_on ^= 1U;
		xTaskDelayUntil(&last_wake_time, config->period);
	}
}

void vAssertCalled(const char *file, int line)
{
	(void)file;
	(void)line;
	taskDISABLE_INTERRUPTS();

	for (;;)
	{
	}
}

void vApplicationMallocFailedHook(void)
{
	vAssertCalled(__FILE__, __LINE__);
}

void vApplicationStackOverflowHook(TaskHandle_t task, char *task_name)
{
	(void)task;
	(void)task_name;
	vAssertCalled(__FILE__, __LINE__);
}

int main(void)
{
	led_init();

	configASSERT(xTaskCreate(led_task, "LED green", 128U,
		(void *)&led_task_config[0], 1U, NULL) == pdPASS);
	configASSERT(xTaskCreate(led_task, "LED orange", 128U,
		(void *)&led_task_config[1], 1U, NULL) == pdPASS);
	configASSERT(xTaskCreate(led_task, "LED red", 128U,
		(void *)&led_task_config[2], 1U, NULL) == pdPASS);
	configASSERT(xTaskCreate(led_task, "LED blue", 128U,
		(void *)&led_task_config[3], 1U, NULL) == pdPASS);

	vTaskStartScheduler();

	/* Reaching here means the scheduler could not allocate the idle task. */
	for (;;)
	{
	}
}
